//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36119
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwKeeperPC {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResPw {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPw() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PwKeeperPC.ResPw", typeof(ResPw).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NewSite.
        /// </summary>
        internal static string sNew {
            get {
                return ResourceManager.GetString("sNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No COM ports found!.
        /// </summary>
        internal static string sNoCom {
            get {
                return ResourceManager.GetString("sNoCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper not found!.
        /// </summary>
        internal static string sNoPw {
            get {
                return ResourceManager.GetString("sNoPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper password mismatch!.
        /// </summary>
        internal static string sPwBad {
            get {
                return ResourceManager.GetString("sPwBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper loggin in....
        /// </summary>
        internal static string sPwLogin {
            get {
                return ResourceManager.GetString("sPwLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper password mismatch! Set new password?.
        /// </summary>
        internal static string sPwNew {
            get {
                return ResourceManager.GetString("sPwNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper writing new password....
        /// </summary>
        internal static string sPwNewDo {
            get {
                return ResourceManager.GetString("sPwNewDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper read failed!.
        /// </summary>
        internal static string sPwReadFail {
            get {
                return ResourceManager.GetString("sPwReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper read ok!.
        /// </summary>
        internal static string sPwReadOk {
            get {
                return ResourceManager.GetString("sPwReadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writing data....
        /// </summary>
        internal static string sPwWr {
            get {
                return ResourceManager.GetString("sPwWr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper write failed!.
        /// </summary>
        internal static string sPwWrBad {
            get {
                return ResourceManager.GetString("sPwWrBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PwKeeper write OK!.
        /// </summary>
        internal static string sPwWrOk {
            get {
                return ResourceManager.GetString("sPwWrOk", resourceCulture);
            }
        }
    }
}
